name: flutterdemo
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  shimmer: ^1.1.1
  http: ^0.12.0
  backdrop: ^0.2.16
  rabbit_converter: ^0.0.1

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_localized_locales: ^1.1.1
  rally_assets: ^2.0.0
  meta:
  scoped_model:
  shrine_images: ^1.1.2
  flare_flutter: ^2.0.2
  url_launcher: ^5.1.6
  shared_preferences: ^0.5.4
  collection: ^1.14.0
  flutter_gallery_assets: ^0.2.0
  package_info: ^0.4.0
  google_fonts: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/png/bg.jpg
    - assets/png/drawerhead.png
    - assets/png/bbb.png
    - assets/png/ccc.png
    - assets/png/ddd.png
    - assets/png/eee.png
    - assets/png/fff.jpg
    - assets/png/ggg.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf



